In [1]:
import pandas as pd
import numpy as np


# Data

In [2]:
B = pd.read_parquet('./data/B_HKML.parquet')
B = B[B['date'] < '2022-05-01']
X_df = pd.read_parquet('./data/X_HKML.parquet')
X_df = X_df[X_df['date'] < '2022-05-01']
y_df = pd.read_parquet('./data/Y_HKML.parquet')
y_df = y_df.iloc[X_df.index]

# Gaussianize target

In [3]:
import sys
#import seaborn as seaborn
sys.path.insert(1, "../../Feature engg/feature-engineering/src")
from class_ import Data

In [4]:
y_date = pd.concat([X_df['date'], y_df], axis=1)
data = Data(f_matrix=y_date, b_matrix=B)
data.gaussianize()
data.standardize()
y_date = data.f_matrix
y_df = y_date['target_w']

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
moons = X_df.date.unique()
batches = 7

# define kernels

In [10]:
from sklearn.gaussian_process.kernels import RBF
from sklearn.gaussian_process.kernels import Matern

# Model - Ridge regression --> kernel - linear

In [11]:
from sklearn.kernel_ridge import KernelRidge


In [13]:
krr = KernelRidge(alpha=1.0)
for i in range(batches):
    X = X_df[X_df['date'] == moons[i]].drop('date', axis=1)
    y = y_df.iloc[X.index]
    krr.fit(X, y)
    print('In Sample')
    print(np.corrcoef(krr.predict(X), y))
    #for j in range(10):
    #    X = X_df[X_df['date'] == moons[(i+1)*35+1+j]].drop('date', axis=1)
    #    y = y_df.iloc[X.index]
    #    y_hat = krr.predict(X)
    #    print('Out of Sample')
    #    print(np.corrcoef(y_hat, y))

In Sample
[[1.         0.46577663]
 [0.46577663 1.        ]]
In Sample
[[1.         0.51182408]
 [0.51182408 1.        ]]
In Sample
[[1.         0.53489272]
 [0.53489272 1.        ]]
In Sample
[[1.         0.46260221]
 [0.46260221 1.        ]]
In Sample
[[1.         0.46810727]
 [0.46810727 1.        ]]
In Sample
[[1.         0.47238535]
 [0.47238535 1.        ]]
In Sample
[[1.         0.48080387]
 [0.48080387 1.        ]]


# Model - Ridge regression --> kernel - RBF

In [29]:
krr = KernelRidge(kernel = "rbf")
for i in range(batches):
    X = X_df[X_df['date'] == moons[i]].drop('date', axis=1)
    y = y_df.iloc[X.index]
    krr.fit(X, y)
    print('In Sample')
    print(np.corrcoef(krr.predict(X), y))
    #for j in range(10):
    #    X = X_df[X_df['date'] == moons[(i+1)*35+1+j]].drop('date', axis=1)
    #    y = y_df.iloc[X.index]
    #    y_hat = krr.predict(X)
    #    print('Out of Sample')
    #    print(np.corrcoef(y_hat, y))

In Sample
[[1.         0.95400228]
 [0.95400228 1.        ]]
In Sample
[[1.         0.96348944]
 [0.96348944 1.        ]]
In Sample
[[1.        0.9601919]
 [0.9601919 1.       ]]
In Sample
[[1.         0.96856413]
 [0.96856413 1.        ]]
In Sample
[[1.         0.95172703]
 [0.95172703 1.        ]]
In Sample
[[1.         0.95723019]
 [0.95723019 1.        ]]
In Sample
[[1.         0.94766042]
 [0.94766042 1.        ]]


# Model - Ridge regression --> kernel - Matern

In [ ]:
['laplacian', 'rbf', 'precomputed', 'chi2', 'poly', 'linear', 'sigmoid', 'additive_chi2', 'polynomial', 'cosine']

In [34]:
krr = KernelRidge(kernel = "polynomial")
for i in range(batches):
    X = X_df[X_df['date'] == moons[i]].drop('date', axis=1)
    y = y_df.iloc[X.index]
    krr.fit(X, y)
    #print(kern)
    print(np.corrcoef(krr.predict(X), y))
    #for j in range(10):
    #    X = X_df[X_df['date'] == moons[(i+1)*35+1+j]].drop('date', axis=1)
    #    y = y_df.iloc[X.index]
    #    y_hat = krr.predict(X)
    #    print('Out of Sample')
    #    print(np.corrcoef(y_hat, y))

chi2
[[1.         0.98703398]
 [0.98703398 1.        ]]
chi2
[[1.         0.98979136]
 [0.98979136 1.        ]]
chi2
[[1.         0.99102009]
 [0.99102009 1.        ]]
chi2
[[1.        0.9913731]
 [0.9913731 1.       ]]
chi2
[[1.         0.98574529]
 [0.98574529 1.        ]]
chi2
[[1.         0.98749102]
 [0.98749102 1.        ]]
chi2
[[1.         0.98571891]
 [0.98571891 1.        ]]


# Model - GP regression --> kernel - linear

In [21]:
from sklearn.gaussian_process import GaussianProcessRegressor


# Model - GP regression --> kernel - RBF

In [36]:
gaussian_process = GaussianProcessRegressor(kernel= RBF())
for i in range(batches):
    X = X_df[X_df['date'] == moons[i]].drop('date', axis=1)
    y = y_df.iloc[X.index]
    gaussian_process.fit(X, y)
    print('In Sample')
    print(np.corrcoef(gaussian_process.predict(X), y))
    #for j in range(10):
    #    X = X_df[X_df['date'] == moons[(i+1)*35+1+j]].drop('date', axis=1)
    #    y = y_df.iloc[X.index]
    #    y_hat = krr.predict(X)
    #    print('Out of Sample')
    #    print(np.corrcoef(y_hat, y))

In Sample
[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]


/Users/utkarshpratiush/Cr_D/Feature engg/c_dao_env/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:1537: RuntimeWarning: underflow encountered in exp
  K = np.exp(-0.5 * dists)
/Users/utkarshpratiush/Cr_D/Feature engg/c_dao_env/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:1552: RuntimeWarning: underflow encountered in multiply
  K_gradient = (K * squareform(dists))[:, :, np.newaxis]


In Sample


/Users/utkarshpratiush/Cr_D/Feature engg/c_dao_env/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:1545: RuntimeWarning: underflow encountered in exp
  K = np.exp(-0.5 * dists)


[[1. 1.]
 [1. 1.]]


/Users/utkarshpratiush/Cr_D/Feature engg/c_dao_env/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:1537: RuntimeWarning: underflow encountered in exp
  K = np.exp(-0.5 * dists)
/Users/utkarshpratiush/Cr_D/Feature engg/c_dao_env/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:1552: RuntimeWarning: underflow encountered in multiply
  K_gradient = (K * squareform(dists))[:, :, np.newaxis]


In Sample


/Users/utkarshpratiush/Cr_D/Feature engg/c_dao_env/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:1545: RuntimeWarning: underflow encountered in exp
  K = np.exp(-0.5 * dists)


[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]


# Model - GP regression --> kernel - Matern

In [38]:
gaussian_process = GaussianProcessRegressor(kernel = Matern())
for i in range(batches):
    X = X_df[X_df['date'] == moons[i]].drop('date', axis=1)
    y = y_df.iloc[X.index]
    gaussian_process.fit(X, y)
    print('In Sample')
    print(np.corrcoef(gaussian_process.predict(X), y))
    #for j in range(10):
    #    X = X_df[X_df['date'] == moons[(i+1)*35+1+j]].drop('date', axis=1)
    #    y = y_df.iloc[X.index]
    #    y_hat = krr.predict(X)
    #    print('Out of Sample')
    #    print(np.corrcoef(y_hat, y))

In Sample
[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]
In Sample
[[1. 1.]
 [1. 1.]]
